version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8871:80"
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: project_app

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "toolkit"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "8101:5432"
    container_name: project_db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: project_redis
